[project]
name = "rj_smi__siscob"
version = "0.1.0"
description = "Pipeline siscob da secretaria smi"
dependencies = [
    "prefect_rj_iplanrio",
]

[tool.uv.sources]
prefect_rj_iplanrio = { workspace = true }
