[project]
name = "rj_cgm__osinfo_rh"
version = "0.1.0"
description = "Pipeline osinfo_rh da secretaria cgm"
dependencies = [
    "prefect_rj_iplanrio",
]

[tool.uv.sources]
prefect_rj_iplanrio = { workspace = true }
