[project]
name = "rj_segovi__dump_db_1746"
version = "0.1.0"
description = "Pipeline dump_db_1746 da secretaria segovi"
dependencies = [
    "prefect_rj_iplanrio",
]

[tool.uv.sources]
prefect_rj_iplanrio = { workspace = true }
