[project]
name = "rj_cvl__arquivo_virtual"
version = "0.1.0"
description = "Pipeline arquivo_virtual da secretaria cvl"
dependencies = [
    "prefect_rj_iplanrio",
]

[tool.uv.sources]
prefect_rj_iplanrio = { workspace = true }
