[project]
name = "rj_pic__disparos_email"
version = "0.1.0"
description = "Pipeline disparos_email da secretaria pic"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.2",
    "python-dotenv>=1.0.0",
    "google-cloud-bigquery>=3.25.0",
]
