[project]
name = "rj_sme__educacao_basica"
version = "0.1.0"
description = "Pipeline educacao_basica da secretaria sme"
dependencies = [
    "prefect_rj_iplanrio",
]

[tool.uv.sources]
prefect_rj_iplanrio = { workspace = true }
